[project]
name = "kneemorph"
version = "0.1.0"
description = "Template mesh mapping using the geodesic-based Bayesian coherent point drift algorithm"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "numpy>=2.3.5",
  "vtk>=9.5.2",
]
